version: "3.8"

services:
  express-app:
    image: rtardo/express-app:latest
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - watchtower

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower