version: '3.8'

services:
  backend:
    environment:
      - REDIS_HOST=redis
    build: ./be
    container_name: backend
    ports:
      - 8080:8080
  frontend:
    build: ./fe
    container_name: frontend
    ports:
      - 5000:5000
  redis:
    image: redis
    container_name: cache
    restart: unless-stopped