version: '3.8'

services:
  nginx:
    environment:
    - NGINX_HOST=http://localhost:80
    image: nginx
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  backend:
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
    build: ./be
    container_name: backend
    depends_on:
      - postgres
      - redis
    ports:
      - 8080
  frontend:
    build: ./fe
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 5000
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    container_name: database
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: cache
    restart: unless-stopped